version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/sources/tadis-analyzer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/sources/tadis-ui"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/sources/custom-example-analyzer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/sources/tadis-ui"
    schedule:
      interval: "weekly"
