name: Build and Push Docker Image

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: tadis-ui

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      if: github.ref_name == 'main' || github.ref_name == 'master' || github.ref_name == 'dev' || startsWith(github.ref, 'refs/tags/v')
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and Push Docker image
      id: push
      uses: docker/build-push-action@v4
      with:
        context: ./sources/tadis-ui
        file: ./sources/tadis-ui/Dockerfile
        push: ${{ github.ref_name == 'main' || github.ref_name == 'master' || github.ref_name == 'dev' || startsWith(github.ref, 'refs/tags/v') }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
