name: Publish to NPM Registry

on:
  workflow_dispatch:
  # Triggered by semantic-release
  push:
    tags:
      - "v*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

      # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
      working-directory: ./sources/tadis-analyzer
    - run: |
        TAG_VERSION="${GITHUB_REF#refs/tags/v}"
        npm version "$TAG_VERSION"
      working-directory: ./sources/tadis-analyzer
    - run: npm publish --provenance --access public
      working-directory: ./sources/tadis-analyzer
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
